Added support for CUDA to CMake build system
pyre/pyre pull request #93
Opened 2023-04-04 10:06 UTC by biancagi

2023-04-07 15:49 UTC, aivazis requested changes

2023-04-07 15:49 UTC, aivazis commented on CMakeLists.txt
shouldn't the `if(${xxx})` really be `if(xxx)  ...  endif(xxx)`? can you remind me the difference between the if with the expanded vs raw variable name?

2023-04-10 15:34 UTC, biancagi commented on CMakeLists.txt
According to the CMake [documentation](https://cmake.org/cmake/help/v3.0/command/if.html), the `if` command was written very early in CMake’s history, predating the `${}` variable evaluation syntax, and therefore evaluates variables named by its arguments. 

The difference between statements `if(${xxx})` and `if(xxx)` is that the first will result in the behavior for constants, namely: 

`if(<constant>)`
_"True if the constant is 1, ON, YES, TRUE, Y, or a non-zero number. False if the constant is 0, OFF, NO, FALSE, N, IGNORE, NOTFOUND, the empty string, or ends in the suffix -NOTFOUND. Named boolean constants are case-insensitive. If the argument is not one of these constants, it is treated as a variable."_

while the second will result in the behavior for variables:

`if(<variable>)`
_"True if the variable is defined to a value that is not a false constant. False otherwise. (Note macro arguments are not variables.)"_

The two behaviors are actually equivalent in most practical cases. However, the CMake documentation provides an intricate example in which the two behaviors differ, which I report below:

The following code:
```
set(var1 OFF)
set(var2 "var1")
if(${var2})
```
appears to the `if` command as: `if(var1)` and is evaluated according to the `if(<variable>)` case documented above. The result is OFF which is false. However, if we remove the ${} from the example then the command sees `if(var2)`, which is true because `var2` is defined to `“var1”` which is not a false constant. 

In light of the above example, I think the `if(${xxx})` syntax is safer. This syntax is also consistent with other calls to the `if` statement that I found in CMake files in pyre (see for example line 91 of the main CMakeLists.txt). 
However, I do not feel strongly about one choice or the other, so please let me know if you request switching to the other syntax.

2023-04-28 07:41 UTC, aivazis commented on CMakeLists.txt
got it. thanks for the explanation

2023-04-28 07:41 UTC, aivazis approved these changes

2023-04-28 07:44 UTC, aivazis approved these changes

2023-04-28 07:45 UTC, merged